---
title: " "
#author: "Subbagian Registrasi dan Statistik Untirta"
#date: "Diupdate pada: `r format(Sys.Date(), '%d %B %Y')`"
output:
  html_document:
    toc: no
    toc_depth: '2'
    df_print: paged
    theme: spacelab
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '2'
---

```{=html}
<style type="text/css">

body{ /* Normal  */
      font-size: 14px;
  }
td {  /* Table  */
  font-size: 12px;
}
h1.title {
  font-size: 28px;
  color: Maroon;
}
h1 { /* Header 1 */
  font-size: 24px;
  color: Maroon;
  font-weight: bold;
}
h2 { /* Header 2 */
  font-size: 20px;
  color: Maroon;
  font-weight: bold;
}
h3 { /* Header 3 */
  font-size: 16px;
#  font-family: "Times New Roman", Times, serif;
  color: Maroon;
  font-weight: bold;
}
h4 { /* Header 4 */
  font-size: 14px;
  color: Maroon;
  font-weight: bold;
}
code.r{ /* Code block */
    font-size: 12px;
}
pre { /* Code block - determines code spacing between lines */
    font-size: 12px;
}
</style>
```
## LAPORAN REKAPITULASI PENDAFTAR JALUR MASUK UJIAN MANDIRI UNTIRTA<br>DIPLOMA (D3) DAN ALIH JENJANG (S1)<br>TAHUN 2021/2022<br><br><br>

```{r message=FALSE, warning=FALSE, echo=FALSE, include=FALSE}
Sys.setlocale("LC_TIME", "IND")
library(readxl)
library(tidyverse)
library(janitor)
library(kableExtra)
master <- data.frame(prodi = c("AKUNTANSI D3", "MANAJEMEN PEMASARAN (D3)", "PERBANKAN DAN KEUANGAN", "PERPAJAKAN", "KEPERAWATAN D3", "MANAJEMEN", "AKUNTANSI"),
                     jalur = c(rep("UMM", 5), rep("JAJ", 2)),
                     fakultas = c(rep("FEB", 4), "KEDOKTERAN", "FEB", "FEB"))
umm <- read_excel("umm.xlsx", skip = 2)
jaj <- read_excel("jaj.xlsx", skip = 2)

data <- rbind(umm[,c(4, 7, 8)], jaj[, c(4, 7, 8)])
names(data) <- c("jalur_masuk", "pil_1", "pil_2")

data <- left_join(data, master, by = c("pil_1" = "prodi"))
data <- data[, c(1, 5, 2, 3)]

data <- pivot_longer(data, cols = starts_with("pil"), names_to = "pilihan")

data <- data[complete.cases(data), ]

data <- data %>% 
  group_by(jalur_masuk, fakultas,  value, pilihan) %>%
  summarise(n = n())

data <- pivot_wider(data, names_from = pilihan, values_from = n)

names(data) <- c("Jalur Masuk", "Fakultas", "Program Studi", "Pilihan 1", 'Pilihan 2')
data[is.na(data)] <- 0
data <- adorn_totals(data, where = "row", name = "Total")

```

Sampai dengan `r format(Sys.time(), "%d %B %Y")` pukul `r format(Sys.time(), "%X")`<br><br>

```{r message=FALSE, warning=FALSE, echo=FALSE}
DT::datatable(data, rownames = F, options = list())
```
